@echo off
REM ============================================
REM  cat - generated by shellmap
REM  Concatenate and print files
REM  Prefer: bat | Fallback: type
REM  Generated: 2026-01-14 21:18
REM ============================================

where bat >nul 2>&1
if %errorlevel%==0 (
    bat %*
    exit /b %errorlevel%
)

REM Fallback to native command
type %*
