@echo off
REM ============================================
REM  clear - generated by shellmap
REM  Clear terminal screen
REM  Maps to: cls
REM  Generated: 2026-01-14 21:18
REM ============================================

cls %*
