@echo off
REM ============================================
REM  cp - generated by shellmap
REM  Copy files
REM  Maps to: copy
REM  Generated: 2026-01-14 21:18
REM ============================================

copy %*
