@echo off
REM ============================================
REM  df - generated by shellmap
REM  Disk space usage
REM  Maps to: wmic logicaldisk get size,freespace,caption
REM  Generated: 2026-01-14 21:18
REM ============================================

wmic logicaldisk get size,freespace,caption %*
