@echo off
REM ============================================
REM  diff - generated by shellmap
REM  Compare files
REM  Prefer: delta → diff | Fallback: fc
REM  Generated: 2026-01-14 21:18
REM ============================================

where delta >nul 2>&1
if %errorlevel%==0 (
    delta %*
    exit /b %errorlevel%
)

where diff >nul 2>&1
if %errorlevel%==0 (
    diff %*
    exit /b %errorlevel%
)

REM Fallback to native command
fc %*
