@echo off
REM ============================================
REM  du - generated by shellmap
REM  Directory disk usage
REM  Prefer: dust → dua | Fallback: dir /s
REM  Generated: 2026-01-14 21:18
REM ============================================

where dust >nul 2>&1
if %errorlevel%==0 (
    dust %*
    exit /b %errorlevel%
)

where dua >nul 2>&1
if %errorlevel%==0 (
    dua %*
    exit /b %errorlevel%
)

REM Fallback to native command
dir /s %*
