@echo off
REM ============================================
REM  env - generated by shellmap
REM  Show environment variables
REM  Maps to: set
REM  Generated: 2026-01-14 21:18
REM ============================================

set %*
