@echo off
REM ============================================
REM  find - generated by shellmap
REM  Find files
REM  Prefer: fd → fzf | Fallback: dir /s /b
REM  Generated: 2026-01-14 21:18
REM ============================================

where fd >nul 2>&1
if %errorlevel%==0 (
    fd %*
    exit /b %errorlevel%
)

where fzf >nul 2>&1
if %errorlevel%==0 (
    fzf %*
    exit /b %errorlevel%
)

REM Fallback to native command
dir /s /b %*
