@echo off
REM ============================================
REM  free - generated by shellmap
REM  Memory usage
REM  Maps to: systeminfo | findstr Memory
REM  Generated: 2026-01-14 21:18
REM ============================================

systeminfo | findstr Memory %*
