@echo off
REM ============================================
REM  grep - generated by shellmap
REM  Search text patterns
REM  Prefer: rg → grep | Fallback: findstr
REM  Generated: 2026-01-14 21:18
REM ============================================

where rg >nul 2>&1
if %errorlevel%==0 (
    rg %*
    exit /b %errorlevel%
)

where grep >nul 2>&1
if %errorlevel%==0 (
    grep %*
    exit /b %errorlevel%
)

REM Fallback to native command
findstr %*
