@echo off
REM ============================================
REM  head - generated by shellmap
REM  Output first part of files
REM  Prefer: bat -r :10 | Fallback: more
REM  Generated: 2026-01-14 21:18
REM ============================================

where bat >nul 2>&1
if %errorlevel%==0 (
    bat -r :10 %*
    exit /b %errorlevel%
)

REM Fallback to native command
more %*
