@echo off
REM ============================================
REM  history - generated by shellmap
REM  Command history
REM  Maps to: doskey /history
REM  Generated: 2026-01-14 21:18
REM ============================================

doskey /history %*
