@echo off
REM ============================================
REM  hostname - generated by shellmap
REM  System hostname
REM  Maps to: hostname
REM  Generated: 2026-01-14 21:18
REM ============================================

hostname %*
