@echo off
REM ============================================
REM  ifconfig - generated by shellmap
REM  Network interface config
REM  Maps to: ipconfig
REM  Generated: 2026-01-14 21:18
REM ============================================

ipconfig %*
