@echo off
REM ============================================
REM  kill - generated by shellmap
REM  Kill process by PID
REM  Maps to: taskkill /PID
REM  Generated: 2026-01-14 21:18
REM ============================================

taskkill /PID %*
