@echo off
REM ============================================
REM  killall - generated by shellmap
REM  Kill process by name
REM  Maps to: taskkill /IM
REM  Generated: 2026-01-14 21:18
REM ============================================

taskkill /IM %*
