@echo off
REM ============================================
REM  less - generated by shellmap
REM  Page through file
REM  Prefer: bat → less | Fallback: more
REM  Generated: 2026-01-14 21:18
REM ============================================

where bat >nul 2>&1
if %errorlevel%==0 (
    bat %*
    exit /b %errorlevel%
)

where less >nul 2>&1
if %errorlevel%==0 (
    less %*
    exit /b %errorlevel%
)

REM Fallback to native command
more %*
