@echo off
REM ============================================
REM  ln - generated by shellmap
REM  Create symbolic link
REM  Maps to: mklink
REM  Generated: 2026-01-14 21:18
REM ============================================

mklink %*
