@echo off
REM ============================================
REM  ls - generated by shellmap
REM  List directory contents
REM  Prefer: yazi → lsd → eza | Fallback: dir
REM  Generated: 2026-01-14 21:18
REM ============================================

where yazi >nul 2>&1
if %errorlevel%==0 (
    yazi %*
    exit /b %errorlevel%
)

where lsd >nul 2>&1
if %errorlevel%==0 (
    lsd %*
    exit /b %errorlevel%
)

where eza >nul 2>&1
if %errorlevel%==0 (
    eza %*
    exit /b %errorlevel%
)

REM Fallback to native command
dir %*
