@echo off
REM ============================================
REM  man - generated by shellmap
REM  Manual pages
REM  Prefer: tldr | Fallback: help
REM  Generated: 2026-01-14 21:18
REM ============================================

where tldr >nul 2>&1
if %errorlevel%==0 (
    tldr %*
    exit /b %errorlevel%
)

REM Fallback to native command
help %*
