@echo off
REM ============================================
REM  mv - generated by shellmap
REM  Move/rename files
REM  Maps to: move
REM  Generated: 2026-01-14 21:18
REM ============================================

move %*
