@echo off
REM ============================================
REM  nano - generated by shellmap
REM  Text editor
REM  Prefer: nvim → vim → nano | Fallback: notepad
REM  Generated: 2026-01-14 21:18
REM ============================================

where nvim >nul 2>&1
if %errorlevel%==0 (
    nvim %*
    exit /b %errorlevel%
)

where vim >nul 2>&1
if %errorlevel%==0 (
    vim %*
    exit /b %errorlevel%
)

where nano >nul 2>&1
if %errorlevel%==0 (
    nano %*
    exit /b %errorlevel%
)

REM Fallback to native command
notepad %*
