@echo off
REM ============================================
REM  pbcopy - generated by shellmap
REM  Copy to clipboard
REM  Maps to: clip
REM  Generated: 2026-01-14 21:18
REM ============================================

clip %*
