@echo off
REM ============================================
REM  printenv - generated by shellmap
REM  Print environment variables
REM  Maps to: set
REM  Generated: 2026-01-14 21:18
REM ============================================

set %*
