@echo off
REM ============================================
REM  ps - generated by shellmap
REM  List running processes
REM  Prefer: procs | Fallback: tasklist
REM  Generated: 2026-01-14 21:18
REM ============================================

where procs >nul 2>&1
if %errorlevel%==0 (
    procs %*
    exit /b %errorlevel%
)

REM Fallback to native command
tasklist %*
