@echo off
REM ============================================
REM  pwd - generated by shellmap
REM  Print working directory
REM  Maps to: cd
REM  Generated: 2026-01-14 21:18
REM ============================================

cd %*
