@echo off
REM ============================================
REM  reboot - generated by shellmap
REM  Reboot system
REM  Maps to: shutdown /r /t 0
REM  Generated: 2026-01-14 21:18
REM ============================================

shutdown /r /t 0 %*
