@echo off
REM ============================================
REM  rm - generated by shellmap
REM  Remove files
REM  Maps to: del
REM  Generated: 2026-01-14 21:18
REM ============================================

del %*
