@echo off
REM ============================================
REM  shutdown - generated by shellmap
REM  Shutdown system
REM  Maps to: shutdown /s /t 0
REM  Generated: 2026-01-14 21:18
REM ============================================

shutdown /s /t 0 %*
