@echo off
REM ============================================
REM  tail - generated by shellmap
REM  Output last part of files
REM  Maps to: more
REM  Generated: 2026-01-14 21:18
REM ============================================

more %*
