@echo off
REM ============================================
REM  top - generated by shellmap
REM  System monitor
REM  Prefer: btm → htop | Fallback: tasklist /v
REM  Generated: 2026-01-14 21:18
REM ============================================

where btm >nul 2>&1
if %errorlevel%==0 (
    btm %*
    exit /b %errorlevel%
)

where htop >nul 2>&1
if %errorlevel%==0 (
    htop %*
    exit /b %errorlevel%
)

REM Fallback to native command
tasklist /v %*
