@echo off
REM ============================================
REM  traceroute - generated by shellmap
REM  Trace packet route
REM  Maps to: tracert
REM  Generated: 2026-01-14 21:18
REM ============================================

tracert %*
