@echo off
REM ============================================
REM  uname - generated by shellmap
REM  System information
REM  Maps to: ver
REM  Generated: 2026-01-14 21:18
REM ============================================

ver %*
