@echo off
REM ============================================
REM  uptime - generated by shellmap
REM  System uptime
REM  Maps to: net statistics workstation
REM  Generated: 2026-01-14 21:18
REM ============================================

net statistics workstation %*
