@echo off
REM ============================================
REM  wget - generated by shellmap
REM  Download files
REM  Prefer: curl -O → wget | Fallback: curl -O
REM  Generated: 2026-01-14 21:18
REM ============================================

where curl >nul 2>&1
if %errorlevel%==0 (
    curl -O %*
    exit /b %errorlevel%
)

where wget >nul 2>&1
if %errorlevel%==0 (
    wget %*
    exit /b %errorlevel%
)

REM Fallback to native command
curl -O %*
