@echo off
REM ============================================
REM  which - generated by shellmap
REM  Locate a command
REM  Maps to: where
REM  Generated: 2026-01-14 21:18
REM ============================================

where %*
