@echo off
REM ============================================
REM  whoami - generated by shellmap
REM  Current username
REM  Maps to: whoami
REM  Generated: 2026-01-14 21:18
REM ============================================

whoami %*
