@echo off
REM ============================================
REM  xdg-open - generated by shellmap
REM  Open file with default app
REM  Maps to: start
REM  Generated: 2026-01-14 21:18
REM ============================================

start %*
